### ISSUE TITLE
should hook methods denoted by symbols be marked as non-writable when extracted from the instance?

### ISSUE THREAD

**Issue by caridy** [tc39/proposal-realms#12]
`Realm.indirectEval` and `Realm.DirectEval` hooks are cached during the constructor invocation, and successive attempts to change them will have no effects, should they be marked as non-writable?

``` js
const o = new Realm();
o[Realm.indirectEval] = function (x) { throw new Error('...') };
o.eval('1'); // will not throw 
```

**Comment by erights** [comment]
Yes. It prevents an easy misunderstanding from causing a confusing mistake. (Related to https://github.com/caridy/proposal-realms/issues/13#issuecomment-228771885 but different.)

There's no loss of generality compared to genuine, non-snapshotted change, since one can pre-install a hook method that delegates to something changeable.

**Comment by caridy** [comment]
Not longer relevant after https://github.com/tc39/proposal-realms/pull/50

**Comment by caridy** [comment]
#50
