### ISSUE TITLE
should `get intrinsics` be frozen?

### ISSUE THREAD

**Issue by caridy** [tc39/proposal-realms#13]
``` js
let intrinsics = myRealmObj.intrinsics;
intrinsics.Array = MyArray;
```

`intrinsics.Array` assignment has no side effect on the realm obj.

**Comment by erights** [comment]
Looking across languages, when a reflective operation returns a meta-level description of some base-level stuff, the pleasant choices are:
  * The mirrors causal connection, where changes to the description are immediately reflected as changes to the object, and vice versa.
  * Having the description be a readonly* view, where changes to the base-level stuff is immediately reflected in the description, but not vice versa.
  * Having the description be an immutable* snapshot.

In JavaScript we have to date selected none of these, but rather a mutable snapshot. IMO this was a mistake we should stop repeating. In particular, `Object.getOwnPropertyDescriptor` should have returned an immutable* snapshot. So yes, I think the intrinsic map returned by `get instrinsics` should be immutable*.

\[\*\] By snapshot* and immutable* I do not mean either shallow or deep stability. Rather, that the meta-info be stable (readonly or frozen), but when it reaches base-level values, rather than descriptions of these values, that the values themselves have whatever mutability they have. For `Object.getOwnPropertyDescriptor`, that corresponds simply to (shallow) frozen. The contents of the `value`, `get`, or `'set` fields have whatever mutability those values have.

**Comment by caridy** [comment]
this is not longer an issue since `intrinsics()` is not a method in https://github.com/tc39/proposal-realms/commit/d3831cedf72944d067bc84dd5a2399dadefaa61e
