### ISSUE TITLE
I think I fixed your need to bind.

### ISSUE THREAD

**Issue by FreezePhoenix** [tc39/proposal-realms#187]
Currently, on this github, the realm-shim has various comments in it marked with todo.
I believe that I have solved this one:
```javascript
			// todo: fix `this` binding in Function(). Fixed.
			const src = `(function(${functionParams}){\n${functionBody}\n}).bind(this)`;

			return safeEval(src);
```
It behaves as I would expect.
I dunno if this is what you were looking for, but I think it is.

**Comment by caridy** [comment]
No, that's not what that comment is all about. If I remember correctly, this is about the Function constructor, which is an intrinsic on the new realm. The bind in the piece of code above does nothing since the generated function will be invoked in a controlled manner (look at `safeEval`), with a very well defined this value pointing to the global object for the new realm.
