### ISSUE TITLE
setPrototype on globalThis?

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-realms#287]
What will happen if I run `Object.setPrototypeOf(realm.globalThis, ...)`?

**Comment by littledan** [comment]
Per the current spec, it's fine, the global is *not* an immutable prototype exotic object. Should it be? I don't think Realms are subject to the cross-origin script tag inclusion that motivated the use of an immutable prototype chain for the Web's global objects (since modules require CORS headers). OTOH it might be nice to make this an immutable prototype exotic object, for consistency.

**Comment by Jack-Works** [comment]
So it means I can capture these codes in a Realm by setting the prototype of the global object to a Proxy.

```
a = 1 // PutValue to an unresolvable reference
globalThis.x = 1
// maybe some other statements like top level var or function
```

**Comment by littledan** [comment]
I explained above why this is not a cross-origin data leak: cross-origin module inclusion is specified to have the right CORS headers.

**Comment by ljharb** [comment]
yea, though, this would mean you’d be able to intercept/observe operations that might normally not be observable in browser or node top-level realms. While i think this is fine, it might indeed have prevented some of the recent fixes to PutValue, for example.

**Comment by littledan** [comment]
@caridy explained that it's very important that the prototype of the global object of a Realm is *mutable*, so that Realms can be used to emulate the Web.
