### ISSUE TITLE
A bit more ergonomics under the current isolation realms?

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-realms#300]
The currently isolated realms only have primitives and wrapped callables to be passed.
Although it is already enough for cross-realms communication, it will be quite a pain API to use.

I'm curious if it is possible to add more kinds of items to be wrapped, for example:

- Promise (wrap and forward status changes)
- Generator/AsyncGenerator (with the result object re-created in the current realm and value get wrapped)

**Comment by leobalter** [comment]
This is not what we are pursuing here and goes beyond the goals for ergonomics of a low level API.

We decided this while removing AsyncFunction in #289 and from several iterations over this new proposal. I believe I also made it clear in the TC39 plenary this week that is intentional we are not giving special handlers for non-callable objects.

It would be too much to be wrapped in engine level while this communication is already possible through a membrane framework implementation in user land.
