### ISSUE TITLE
the nature of the realm's global object

### ISSUE THREAD

**Issue by caridy** [tc39/proposal-realms#6]
Questions to be discussed with implementers:
- Can the global object be a proxy?
- Can two realms shared the same global object?

**Comment by jugglinmike** [comment]
Technically speaking, the specification allows for the global "this" value to be an exotic object. In researching how to assert correct behavior in these cases, [I recently raised this issue in the Test262 project](https://github.com/tc39/test262/issues/538). I'd be happy to see this API standardized because it would motivate implementors to expose the mechanisms necessary to test certain portions of ES2015.

But this begs the question: if we need a new API to assert conformance, why does this specification text exists at all? Are there any implementations that define the global "this" value as a Proxy (or other exotic) by default?

**Comment by jugglinmike** [comment]
I'm just now learning about [the WhatWG `WindowProxy` exotic object](https://html.spec.whatwg.org/multipage/browsers.html#windowproxy) (and [some related implementation
concerns](https://esdiscuss.org/topic/figuring-out-the-behavior-of-windowproxy-in-the-face-of-non-configurable-properties)). Maybe this is why that spec text exists? If so, are there still other use cases?

**Comment by caridy** [comment]
Resolution:

* A new Realm creates a new Global Object (to satisfy implementers).
* The Global Object is exotic and can only be used by one Realm instance.
